# Generated by Django 5.0.5 on 2026-02-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogitem',
            options={},
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
