# Generated by Django 5.0.5 on 2026-03-25 23:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_catalogitem_options_alter_catalogitem_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='bricklink_reference_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='lego_reference_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='CatalogCostEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('lego', 'LEGO'), ('bricklink', 'BrickLink'), ('brickowl', 'BrickOwl'), ('ebay', 'eBay'), ('local', 'Local'), ('other', 'Other')], max_length=32)),
                ('supplier_name', models.CharField(blank=True, max_length=120)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('tax_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('other_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('purchased_at', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_entries', to='catalog.catalogitem')),
            ],
            options={
                'ordering': ['-purchased_at', '-id'],
            },
        ),
    ]
