# Generated by Django 5.0.5 on 2026-03-16 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_catalogitem_options_alter_catalogitem_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('location_type', models.CharField(choices=[('warehouse', 'Warehouse'), ('room', 'Room'), ('shelf', 'Shelf'), ('bin', 'Bin'), ('drawer', 'Drawer'), ('tote', 'Tote'), ('other', 'Other')], default='other', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('sealed', 'Sealed'), ('complete', 'Complete'), ('loose', 'Loose'), ('incomplete', 'Incomplete'), ('damaged', 'Damaged')], default='loose', max_length=20)),
                ('source_type', models.CharField(choices=[('lego', 'LEGO'), ('bricklink', 'BrickLink'), ('ebay', 'eBay'), ('thrift', 'Thrift'), ('trade', 'Trade'), ('personal', 'Personal'), ('other', 'Other')], default='other', max_length=20)),
                ('quantity_on_hand', models.PositiveIntegerField(default=0)),
                ('quantity_reserved', models.PositiveIntegerField(default=0)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('acquired_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_sellable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_records', to='catalog.catalogitem')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_records', to='inventory.location')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
