# Generated by Django 5.0.5 on 2026-02-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Minifig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bricklink_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('image_url', models.URLField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_override', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
