# Generated by Django 5.0.5 on 2026-02-04 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_catalogitem_options_alter_catalogitem_notes'),
        ('minifigs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='minifig',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='minifig',
            name='price_override',
        ),
        migrations.AddField(
            model_name='minifig',
            name='catalog_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='minifig', to='catalog.catalogitem'),
        ),
        migrations.AlterField(
            model_name='minifig',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='minifig',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minifigs', to='minifigs.theme'),
        ),
    ]
