# Generated by Django 5.0.5 on 2026-03-15 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minifigs', '0002_theme_remove_minifig_base_price_and_more'),
        ('parts', '0003_alter_partcolor_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinifigIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('role', models.CharField(choices=[('head', 'Head'), ('hair', 'Hair'), ('hat', 'Hat'), ('helmet', 'Helmet'), ('torso', 'Torso'), ('legs', 'Legs'), ('headgear', 'Headgear'), ('accessory', 'Accessory'), ('weapon', 'Weapon'), ('cape', 'Cape'), ('body', 'Body'), ('other', 'Other')], default='other', max_length=30)),
                ('is_required', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('minifig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='minifigs.minifig')),
                ('part_color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='minifig_ingredients', to='parts.partcolor')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='minifigingredient',
            constraint=models.UniqueConstraint(fields=('minifig', 'part_color', 'role', 'sort_order'), name='uniq_minifig_partcolor_role_sort'),
        ),
    ]
