# Generated by Django 5.0.5 on 2026-03-16 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_catalogitem_options_alter_catalogitem_notes'),
        ('minifigs', '0003_minifigingredient_and_more'),
        ('parts', '0003_alter_partcolor_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_num', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('image_url', models.URLField(blank=True)),
                ('piece_count', models.PositiveIntegerField(default=0)),
                ('catalog_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='set', to='catalog.catalogitem')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sets', to='minifigs.theme')),
            ],
            options={
                'ordering': ['set_num', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SetMinifigRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('is_exact_required', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('minifig', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='set_minifig_requirements', to='minifigs.minifig')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minifig_requirements', to='sets.set')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SetPartRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('instruction_page', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_structural', models.BooleanField(default=False)),
                ('is_exact_color_required', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('part_color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='set_part_requirements', to='parts.partcolor')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_requirements', to='sets.set')),
            ],
            options={
                'ordering': ['instruction_page', 'sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='setminifigrequirement',
            constraint=models.UniqueConstraint(fields=('set', 'minifig', 'sort_order'), name='uniq_set_minifig_requirement_row'),
        ),
        migrations.AddConstraint(
            model_name='setpartrequirement',
            constraint=models.UniqueConstraint(fields=('set', 'part_color', 'instruction_page', 'sort_order'), name='uniq_set_part_requirement_row'),
        ),
    ]
