# Generated by Django 5.0.5 on 2026-03-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setminifig',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='setpart',
            name='color_match_mode',
            field=models.CharField(choices=[('exact', 'Exact Color'), ('any_color', 'Any Color')], default='exact', max_length=20),
        ),
    ]
