# Generated by Django 5.0.5 on 2026-03-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
