# Generated by Django 5.0.5 on 2026-04-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setpart',
            name='step_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
