# Generated by Django 5.0.5 on 2026-03-18 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minifigs', '0003_minifigingredient_and_more'),
        ('sets', '0002_setminifig_is_required_setpart_color_match_mode'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='setminifig',
            name='uniq_set_minifig_row',
        ),
        migrations.RemoveConstraint(
            model_name='setpart',
            name='uniq_set_part_row',
        ),
        migrations.AlterField(
            model_name='setminifig',
            name='minifig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='set_minifigs', to='minifigs.minifig'),
        ),
    ]
