# Generated by Django 5.0.5 on 2026-01-31 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lego_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('hex', models.CharField(blank=True, max_length=7)),
                ('is_transparent', models.BooleanField(default=False)),
                ('is_metallic', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('general_category', models.CharField(blank=True, max_length=120)),
                ('specific_category', models.CharField(blank=True, max_length=120)),
                ('actual_category', models.CharField(max_length=50)),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['part_id'],
            },
        ),
        migrations.CreateModel(
            name='PartColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(blank=True, max_length=80)),
                ('part_color_code', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('image_url_1', models.URLField(blank=True)),
                ('image_url_2', models.URLField(blank=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_colors', to='parts.color')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_colors', to='parts.part')),
            ],
            options={
                'ordering': ['part__part_id', 'color__name', 'variant'],
            },
        ),
        migrations.AddConstraint(
            model_name='partcolor',
            constraint=models.UniqueConstraint(fields=('part', 'color', 'variant'), name='uniq_part_color_variant'),
        ),
    ]
