# Generated by Django 5.0.5 on 2026-02-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_partcolor_catalog_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partcolor',
            name='variant',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
