# Generated by Django 5.0.5 on 2026-07-08 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_alter_partcolor_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='partcolor',
            name='root_part_color',
            field=models.ForeignKey(blank=True, help_text='Optional canonical/root PartColor. Use this when older LEGO/BrickLink IDs represent the same usable part-color. Variants inherit the root catalog pricing and count together for build matching.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variant_part_colors', to='parts.partcolor'),
        ),
    ]
